# contents
nav:
  # - Home: index.md
  # - how_to_use.md
  # - setting.md
  # - customize.md
  # - faq.md
  - Title: title.md
  - Service: service.md
  - Ingress: ingress.md
  - Helm: helm.md
  - Kustomize: kustomize.md
  - Monitoring: monitoring.md

# metadata
site_name: Docs
docs_dir: src # document root
repo_url: https://github.com/yasuki0707/kubernetes-study
repo_name: yasuki0707/kubernetes-study
edit_uri: ""

# extensions
markdown_extensions:
  - toc:
      permalink: "#"
  - pymdownx.highlight:
      auto_title: true
      linenums: true
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
# theme
theme:
  name: material
  language: ja
  icon:
    repo: fontawesome/brands/github
  logo: img/logo.png
  favicon: img/logo.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - navigation.indexes
    - search
